name       : calf
version    : 0.90.3
release    : 5
source     :
    - https://github.com/calf-studio-gear/calf/archive/0.90.3.tar.gz : 8781cbd1a81dec59b5923a23141ab2ca74e0e724389e15ffcf3820ace138a46c
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : LV2 plug-in suite and standalone JACK host
description: |
    Calf Studio Gear is an audio plug-in pack for LV2 and JACK environments under LINUX operating systems. The suite contains lots of effects (delay, modulation, signal processing, filters, equalizers, dynamics, distortion and mastering effects), instruments (SF2 player, organ simulator and a monophonic synthesizer) and tools (analyzer, mono/stereo tools, crossovers). Calf Studio Gear aims for a professional audience.
builddeps  :
    - pkgconfig(cairo-egl)
    - pkgconfig(fluidsynth)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(lash-1.0)
    - pkgconfig(lv2)
    - ladspa-devel
setup      : |
    %reconfigure --enable-sse --enable-experimental
build      : |
    %make
install    : |
    %make_install
